name: PR Approval
on:
  pull_request:
    branches:
      - master
    types: [opened] # probably the only one you need


jobs:
  my_job:
    name: Auto-approve
    runs-on: ubuntu-latest
    if: contains(github.ref, 'requests/prod')
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const creator = context.payload.sender.login
            const result = await github.rest.teams.getMembershipForUserInOrg({
              org: context.repo.owner,
              team_slug: 'my-cool-team',
              username: creator
            })
            console.log(creator, result) // do whatever you want
            if (result){
              const approve_result = await github.pulls.createReview({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                event: "APPROVE"
              })
              console.log(approve_result.status)
            }
            console.log(approve_result.status)
